// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transformer.Wars.Models.DB;

namespace Transformer.Wars.Migrations
{
    [DbContext(typeof(TransformerWarsContext))]
    partial class TransformerWarsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Transformer.Wars.Models.DB.AllegianceType", b =>
                {
                    b.Property<int>("AllegianceTypeId");

                    b.Property<string>("AllegianceTypeTitle");

                    b.HasKey("AllegianceTypeId");

                    b.ToTable("AllegianceTypes");

                    b.HasData(
                        new
                        {
                            AllegianceTypeId = 1,
                            AllegianceTypeTitle = "Autobot"
                        },
                        new
                        {
                            AllegianceTypeId = 2,
                            AllegianceTypeTitle = "Decepticon"
                        });
                });

            modelBuilder.Entity("Transformer.Wars.Models.DB.Transformer", b =>
                {
                    b.Property<int>("TransformerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AllegianceTypeId");

                    b.Property<short>("Courage");

                    b.Property<short>("Endurance");

                    b.Property<short>("Firepower");

                    b.Property<short>("Intelligence");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<short>("Rank");

                    b.Property<short>("Skill");

                    b.Property<short>("Speed");

                    b.Property<short>("Strength");

                    b.HasKey("TransformerId");

                    b.HasIndex("AllegianceTypeId");

                    b.ToTable("Transformers");
                });

            modelBuilder.Entity("Transformer.Wars.Models.DB.TransformerScore", b =>
                {
                    b.Property<int>("Score")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Score");

                    b.ToTable("TransformerScores");
                });

            modelBuilder.Entity("Transformer.Wars.Models.DB.Transformer", b =>
                {
                    b.HasOne("Transformer.Wars.Models.DB.AllegianceType", "AllegianceType")
                        .WithMany("Transformers")
                        .HasForeignKey("AllegianceTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
